select nombre from tienda.producto;
select nombre, precio from tienda.producto;
select * from tienda.producto;
select nombre, precio, precio * 1.04 as precio_dolares from producto;
select nombre as "nombre de producto", precio as "euros", precio*1.04 as "dolares" from producto;
select upper(nombre), precio from producto;
select lower(nombre), precio from producto;
select nombre, upper (substring(nombre, 1, 2)) from fabricante;
select nombre, round(precio,0) from producto;
select nombre, truncate(precio, 0) from producto;
select codigo_fabricante from producto;
select distinct codigo_fabricante from producto; 
select nombre from fabricante order by nombre asc;
select nombre from fabricante order by nombre desc;
select nombre, precio from producto order by nombre asc, precio desc;
select nombre from fabricante limit 5;
select * from fabricante limit 3,2;
select nombre, precio from producto order by precio asc limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante = 2;
select p.nombre, p.precio, f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo;
select p.nombre, p.precio, f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo order by f.nombre asc;
select p.codigo, p.nombre, f.codigo, f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo;
select p.nombre, p.precio, f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo order by p.precio asc limit 1;
select p.nombre, p.precio, f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo order by p.precio desc limit 1;
select p.nombre, p.precio, f.nombre from producto as p inner join fabricante as f on p.codigo_fabricante = f.codigo where (f.nombre = "Lenovo");
select producto.nombre, fabricante.nombre as "fabricante", producto.precio from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre = "Crucial" and producto.precio > 200;
select producto.nombre, fabricante.nombre as "fabricante" from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre like "Asus" or fabricante.nombre like "Seagate";
select producto.nombre, fabricante.nombre as "fabricante" from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre IN ("Asus" ,"Hewlett-Packard" , "Seagate");
select producto.nombre, fabricante.nombre as "fabricante" from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre like "%e";
select producto.nombre, fabricante.nombre as "fabricante" from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre like "%w%";
select p.nombre, p.precio, f.nombre from producto p join fabricante f on p.codigo_fabricante = f.codigo where p.precio >= 180 order by p.precio asc, p.nombre desc;
select distinct f.codigo, f.nombre from fabricante f join producto p where p.codigo_fabricante = f.codigo;
select fabricante.nombre as "fabricante", producto.nombre from fabricante left join producto on producto.codigo_fabricante = fabricante.codigo order by fabricante.codigo;
select f.nombre from fabricante f left outer join producto p on p.codigo_fabricante = f.codigo where p.codigo_fabricante is null; /* select fabricante.nombre from fabricante where fabricante.codigo not in (select producto.codigo_fabricante from producto);*/
select producto.nombre, producto.precio, fabricante.nombre as "fabricante" from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre = "Lenovo";
select producto.codigo, producto.nombre, producto.precio, producto.codigo_fabricante, fabricante.nombre as "fabricante" from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where (precio = (select producto.precio from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre = "Lenovo" order by producto.precio desc limit 1));
select producto.nombre, producto.precio, fabricante.nombre as "fabricante" from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre = "Lenovo" order by producto.precio desc limit 1;
select producto.nombre, producto.precio, fabricante.nombre as "fabricante" from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre = "Hewlett-Packard" order by producto.precio asc limit 1;
select producto.nombre, producto.precio, fabricante.nombre as "fabricante" from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where (precio >= (select producto.precio from producto,fabricante where fabricante.codigo = producto.codigo_fabricante and fabricante.nombre = "Lenovo" order by producto.precio desc limit 1));
select f.nombre as "fabricante", p.nombre, p.precio from producto as p inner join fabricante as f on p.codigo_fabricante = f.codigo where (f.nombre = "Asus") and (p.precio > (select avg(p.precio) from producto)); 

